version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/var/src/workspace
      # - /var/src/workspace/node_modules
      - ./node_modules:/var/src/workspace/node_modules
    command: npm run start:app
    restart: always
    hostname: react-app
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 3000:3000

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/var/src/workspace
      # - /var/src/workspace/node_modules
      - ./node_modules:/var/src/workspace/node_modules
    command: npm run start:api
    restart: always
    hostname: api
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 3333:3333

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: mysql_server
    environment:
      MYSQL_DATABASE: 'xano_clone'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'abc@123'      
      MYSQL_ROOT_PASSWORD: 'abc@123'
    ports:
      - '3307:3306'
    networks:
      - backend
      - frontend
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'

networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure